// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Funasr_1.0

#ifndef _FUNASR_1_0_UI_H
#define _FUNASR_1_0_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
void ui_event_startMeeting(lv_event_t * e);
extern lv_obj_t * ui_startMeeting;
void ui_event_endMeeting(lv_event_t * e);
extern lv_obj_t * ui_endMeeting;
void ui_event_Name(lv_event_t * e);
extern lv_obj_t * ui_Name;
extern lv_obj_t * ui_Keyboard1;
void ui_event_AddName(lv_event_t * e);
extern lv_obj_t * ui_AddName;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_307400400);    // assets/开始.png
LV_IMG_DECLARE(ui_img_121628627);    // assets/停止-copy.png
LV_IMG_DECLARE(ui_img_239127470);    // assets/添加人员 (1).png
LV_IMG_DECLARE(ui_img_lamp_28_png);    // assets/lamp_28.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
