// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Funasr_1.0

#ifndef _UI_COMP_STARTMEETING_H
#define _UI_COMP_STARTMEETING_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT startMeeting
#define UI_COMP_STARTMEETING_STARTMEETING 0
#define _UI_COMP_STARTMEETING_NUM 1
lv_obj_t * ui_startMeeting_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
