// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Funasr_1.0

#include "ui.h"


// 声明外部函数（由 .ino 文件实现）
extern void send_signal_open();
void startMeeting(lv_event_t * e)
{
  // Your code here
  send_signal_open();
}


// 声明外部函数（由 .ino 文件实现）
extern void send_signal_close();
void endMeeting(lv_event_t * e)
{
	// Your code here
  send_signal_close();
}




// 声明外部函数（由 .ino 文件实现）
extern void sendTextToServer(const char *text);
void SetName1(lv_event_t * e)
{
	// Your code here
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    const char *text = lv_textarea_get_text(ui_Name);
    sendTextToServer(text);  // 调用发送函数
  }
}
