// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Funasr_1.0

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void startMeeting(lv_event_t * e);
void endMeeting(lv_event_t * e);
void SetName1(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
