// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Funasr_1.0

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_startMeeting = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_startMeeting, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_307400400, NULL);
    lv_obj_set_height(ui_startMeeting, 129);
    lv_obj_set_width(ui_startMeeting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_startMeeting, -15);
    lv_obj_set_y(ui_startMeeting, 50);
    lv_obj_set_align(ui_startMeeting, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_startMeeting, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_endMeeting = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_endMeeting, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_121628627, NULL);
    lv_obj_set_height(ui_endMeeting, 131);
    lv_obj_set_width(ui_endMeeting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_endMeeting, -14);
    lv_obj_set_y(ui_endMeeting, 49);
    lv_obj_set_align(ui_endMeeting, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_endMeeting, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Name = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_Name, 180);
    lv_obj_set_height(ui_Name, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_Name, -272);
    lv_obj_set_y(ui_Name, -158);
    lv_obj_set_align(ui_Name, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_Name, "INPUT YOUR NAME");
    lv_textarea_set_one_line(ui_Name, true);



    ui_Keyboard1 = lv_keyboard_create(ui_Screen1);
    lv_obj_set_width(ui_Keyboard1, 753);
    lv_obj_set_height(ui_Keyboard1, 243);
    lv_obj_set_x(ui_Keyboard1, -4);
    lv_obj_set_y(ui_Keyboard1, 75);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_AddName = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_AddName, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_239127470, NULL);
    lv_obj_set_height(ui_AddName, 56);
    lv_obj_set_width(ui_AddName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_AddName, -89);
    lv_obj_set_y(ui_AddName, -152);
    lv_obj_set_align(ui_AddName, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_startMeeting, ui_event_startMeeting, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_endMeeting, ui_event_endMeeting, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Name, ui_event_Name, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_Name);
    lv_obj_add_event_cb(ui_AddName, ui_event_AddName, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
